default_platform(:ios)

platform :ios do

  desc "Fetch certificates and provisioning profiles"
  lane :fetch_certificates do
    match(
      type: "adhoc",  # Or "appstore", "development", "enterprise"
      readonly: false
    )
  end

  
  desc "Build iOS app"
  lane :build_ios do
    build_app(
      scheme: "TradeFuture",
      export_method: "ad-hoc"
    )
  end

  desc "Upload iOS app to Diawi"
  lane :upload_ios_to_diawi do
    build_ios
    sh "curl https://upload.diawi.com/ -F token=#{ENV['DIAWI_TOKEN']} -F file=@./build/TradeFuture.ipa"
  end
end


platform :android do
  desc "Build Android app"
  lane :build_android do
    gradle(
      task: "assembleRelease",
      project_dir: "./android"
    )
  end

  desc "Upload Android app to Diawi"
  lane :upload_android_to_diawi do
    build_android
    sh "curl https://upload.diawi.com/ -F token=#{ENV['DIAWI_TOKEN']} -F file=@./android/app/build/outputs/apk/release/app-release.apk"
  end
end