project_name= "TradeFuture"
scheme = 'TradeFuture'
build_configuration = "Release"
project_path = "./#{project_name}.xcodeproj"
# export_method = "app-store"
cached_derived_data_path = File.expand_path("../cached_derived_data")
cache_folder = File.expand_path("#{cached_derived_data_path}/Build/Intermediates.noindex/ArchiveIntermediates/#{scheme}/BuildProductsPath/#{build_configuration}-iphoneos")
intermediates_path = "#{cached_derived_data_path}/Build/Intermediates.noindex/ArchiveIntermediates/#{project_name}"

# export_method is either "app-store" or "ad-hoc" depending on where its being sent.
export_method = 'ad-hoc'

# prov_profile is the name of the provisioning profile - ie: "DevOps Distribution v2"
prov_profile = 'tradeFuture'

# view the profile in finder to get the UUID
# prov_profile_uuid = ENV["APPLE_PROV_PROFILE_UUID"]

# signing ID will be automatically set by the CI
signing_identity = ENV["APPLE_CERTIFICATE_SIGNING_IDENTITY"]


diawi_token = ENV['DIAWI_TOKEN']
teamID = ENV['TEAM_ID']


default_platform(:ios)

platform :ios do

  desc "Build iOS app"
  lane :build_ios do

    update_code_signing_settings(
      path:"#{project_name}.xcodeproj",
      use_automatic_signing: false,
      profile_name: prov_profile,
    )

    build_app(
      workspace: "#{project_name}.xcworkspace",
      scheme: project_name,
      # export_xcargs: "-allowProvisioningUpdates",
      export_method: export_method,
      output_directory: "output/package",
      archive_path: "output/archive",
      export_team_id: teamID,
      export_xcargs: "-allowProvisioningUpdates",
      export_options: {
        compileBitcode: false,
        uploadBitcode: false,
        uploadSymbols: false,
        method: export_method,
        stripSwiftSymbols: true,
        teamID: teamID,
        signingStyle: "manual",
        signingCertificate: signing_identity,
        thinning: "<none>",
        provisioningProfiles: {
          "com.tradeFuture.app" => prov_profile
        }
      },
      xcargs: [
        "PROVISIONING_PROFILE_SPECIFIER='#{prov_profile}'",
        "CODE_SIGN_STYLE=Manual",
        "CODE_SIGN_IDENTITY='#{signing_identity}'"
      ].join(" ")
    )
    sh "curl https://upload.diawi.com/ -F token=#{diawi_token} -F file=@./output/package/TradeFuture.ipa"

  end


end