default_platform(:ios)

platform :ios do
  desc "Build iOS app"
  lane :build_ios do
    build_app(
      scheme: "TradeFuture",
      export_method: "ad-hoc"
    )
  end

  desc "Upload iOS app to Diawi"
  lane :upload_ios_to_diawi do
    build_ios
    sh "curl https://upload.diawi.com/ -F token=#{ENV['DIAWI_TOKEN']} -F file=@./build/TradeFuture.ipa"
  end
end