default_platform(:android)

platform :android do
  desc "Build Android app"
  lane :build_android do
    gradle(
      task: "assembleRelease",
      project_dir: "."
    )
  end

  desc "Upload Android app to Diawi"
  lane :upload_android_to_diawi do
    build_android
    sh "curl https://upload.diawi.com/ -F token=#{ENV['DIAWI_TOKEN']} -F file=@./app/build/outputs/apk/release/app-release.apk"
  end
end