name: Build and Upload to Diawi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    
    env:
      DIAWI_TOKEN: ${{ secrets.DIAWI_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install Fastlane
        run: |
          gem install bundler -v 2.4.22
          bundle install

      - name: Build and upload iOS app to Diawi
        run: |
          cd ios
          bundle exec fastlane fetch_certificates
          bundle exec fastlane upload_ios_to_diawi

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Build and upload Android app to Diawi
        run: |
          cd android
          bundle exec fastlane upload_android_to_diawi
