name: iOS Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios
          pod install

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install Fastlane
        run: |
          gem install bundler -v 2.4.22
          bundle install

      - name: Decode and save the .p12 certificate
        run: |
          echo "$IOS_CERTIFICATE_P12" | base64 --decode > certificate.p12
        env:
          IOS_CERTIFICATE_P12: ${{ secrets.IOS_CERTIFICATE_P12 }}

      - name: Install the .p12 certificate
        run: |
          security create-keychain -p mypassword build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p mypassword build.keychain
          security import certificate.p12 -k build.keychain -P "$IOS_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k mypassword build.keychain
        env:
          IOS_CERTIFICATE_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}

      - name: Decode and save the provisioning profile
        run: |
          echo "$IOS_PROVISIONING_PROFILE" | base64 --decode > tradeFuture.mobileprovision
        env:
          IOS_PROVISIONING_PROFILE: ${{ secrets.IOS_PROVISIONING_PROFILE }}

      - name: Install the provisioning profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp tradeFuture.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Verify the provisioning profile installation
        run: |
          ls ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Run fastlane build
        run: |
          cd ios
          bundle exec fastlane build_ios
          cat /Users/runner/Library/Logs/gym/TradeFuture-TradeFuture.log
          mv output ..
          cd ..
        env:
          SIGN_TYPE: 'ad-hoc'
          PROV_PROFILE_NAME: 'tradeFuture'
          APPLE_CERTIFICATE_SIGNING_IDENTITY: 'Apple Distribution: TECXAR CONSULTANTS PRIVATE LIMITED (32864LVP55)'
          DIAWI_TOKEN: 'ayrmyP77RZ13bxeiEJWYQMLNsHY0sjUnRSpkPDzNKl'
          TEAM_ID: '32864LVP55'

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: ios/output/package/TradeFuture.ipa
